name: Action Smoke Test

on:
  push:
    branches: [ main, transport-abstraction ]
  pull_request:
    branches: [ main, transport-abstraction ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run Action Smoke Test
        uses: ./
        with:
          snapshots-dir: 'snapshots'
          server-command: 'python server.py --name "toy server"'
